# Generated by Django 5.1.7 on 2025-11-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
